### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by agungshiro** [Aoi-hosizora/FFDNet_pytorch#4]
I have a problem when running this code with cuda_enable, the error comes up with the state "Cuda running out of memory". I've been watching the process through "htop".  While in the training session it took only 1GB+ , but when it trying to validate (after 5 epochs of training), the error always rises, no matter what size of my training data. DO you have any suggest to solve this problem? Thank you
FYI : My GPU has 4GB of VRAM

**Comment by agungshiro** [comment]
I solved this problem by adding float() on the statement bellow:
train_losses += float(train_loss)
val_losses += float(val_loss)
